package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.38

import (
	"context"

	"github.io/anilk/crane/graph"
	"github.io/anilk/crane/models"
)

// EventID is the resolver for the eventId field.
func (r *eventOrganizerResolver) EventID(ctx context.Context, obj *models.EventOrganizer) (*models.Event, error) {
	event, err := r.EventRepository.FindByID(obj.EventID)

	if err != nil {
		return nil, err
	}

	return event, nil
}

// UserID is the resolver for the userId field.
func (r *eventOrganizerResolver) UserID(ctx context.Context, obj *models.EventOrganizer) (*models.User, error) {
	user, err := r.UserRepository.FindByID(obj.UserID)

	if err != nil {
		return nil, err
	}

	return user, nil
}

// EventOrganizer returns graph.EventOrganizerResolver implementation.
func (r *Resolver) EventOrganizer() graph.EventOrganizerResolver { return &eventOrganizerResolver{r} }

type eventOrganizerResolver struct{ *Resolver }
