package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.38

import (
	"context"

	"github.io/anilk/crane/graph"
	"github.io/anilk/crane/models"
)

// AdminUserID is the resolver for the adminUserId field.
func (r *eventResolver) AdminUserID(ctx context.Context, obj *models.Event) (*models.User, error) {
	user, err := r.UserRepository.FindByID(obj.AdminUserID)

	if err != nil {
		return nil, err
	}

	return user, nil
}

// Event returns graph.EventResolver implementation.
func (r *Resolver) Event() graph.EventResolver { return &eventResolver{r} }

type eventResolver struct{ *Resolver }
